name: 'Build Debian Packages'
description: 'Build both halos and halos-marine metapackages'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build debtools image
      shell: bash
      run: |
        docker compose -f docker/docker-compose.debtools.yml build debtools

    - name: Build halos package
      shell: bash
      run: |
        cd halos
        docker compose -f ../docker/docker-compose.debtools.yml run --rm debtools \
          bash -c "dpkg-buildpackage -b -uc -us && mv ../*.deb ../*.buildinfo ../*.changes ./ 2>/dev/null || true"

    - name: Build halos-marine package
      shell: bash
      run: |
        cd halos-marine
        docker compose -f ../docker/docker-compose.debtools.yml run --rm debtools \
          bash -c "dpkg-buildpackage -b -uc -us && mv ../*.deb ../*.buildinfo ../*.changes ./ 2>/dev/null || true"

    - name: Move packages to root
      shell: bash
      run: |
        mv halos/*.deb ./ 2>/dev/null || true
        mv halos-marine/*.deb ./ 2>/dev/null || true
        ls -lh *.deb
